spring:
  datasource:
    username: demo
    password: 123456
    url: jdbc:mysql://localhost:3306/japp?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456